server:
  port: ${PORT:8761}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
#    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 300

#management:
#  security:
#    enabled: false
#spring:
#  boot:
#    admin:
#      context-path: /admin