server:
  port: ${PORT:8761}

eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: false
    fetch-registry: false
  serviceUrl:
    defaultZone: ${DISCOVERY_URL:http://tk-be-discovery-service:8761/eureka/}
  instance:
    leaseRenewalIntervalInSeconds: 10

management:
  security:
    enabled: false
spring:
  boot:
    admin:
      context-path: /admin